### ISSUE TITLE
Rendre plus clair le côté officiel

### ISSUE THREAD

**Issue by MattiSG** [sgmap/paie-www#1]
Ajouter un header avec logo République Française.

**Comment by indydedeken** [comment]
Un exemple de page avec ce header SGMAP par hasard ? _Images, phrases_ ?

**Comment by MattiSG** [comment]
@indydedeken A minima il s'agit du logo RF, comme sur [mes-aides](http://mes-aides.gouv.fr).
Il est d'ailleurs probablement plus pertinent politiquement de ne pas lier ce projet à une administration spécifique (le SGMAP en étant une). Je vais mettre à jour la description de l'issue.

**Comment by laem** [comment]
Je ne sais pas s'il faut, si l'on peut, intégrer la Marianne. J'imagine que l'on ne peut pas changer sa couleur pour mieux l'intégrer dans la page. 
En attendant, j'ai intégré simplement le texte Secrétariat Général pour la Modernisation de l'Action Publique

**Comment by MattiSG** [comment]
> intégrer la Marianne

C'est au SIG. Utiliser le logo SGMAP. [Refs](https://github.com/sgmap/bonnes-pratiques#identité-visuelle).

**Comment by laem** [comment]
Fait !
